jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Criar arquivo .env
              run: |
                  echo "API_KEY=${{ secrets.API_KEY }}" > .env
                  echo "OUTRO_SEGREDO=${{ secrets.FAKEAPI_KEY }}" >> .env

            - name: Executar seu código
              run: npm start # ou qualquer comando que execute seu código
